/**
 * @fileoverview The player-facing join URL for a tournament (Unit C3).
 *
 * One place builds it, because it is now shown in three: copied from the setup
 * screen, encoded into the printable QR sign, and read aloud off that sign by
 * anyone whose camera won't focus. If those ever disagreed, the typed fallback
 * would quietly send people somewhere the QR doesn't.
 *
 * It encodes `join_token`, NEVER the view-only `share_token` — a spectator
 * holding the share link must not be able to put themselves in the tournament.
 */

/**
 * @param joinToken - `brackets.join_token`, generated by the database on insert.
 * @returns An absolute URL, since it gets printed and typed by hand.
 */
export function joinUrl(joinToken: string): string {
  return `${window.location.origin}/brackets/join/${joinToken}`;
}
