/**
 * @fileoverview Printable join QR sign for a tournament (`/brackets/:id/qr`).
 *
 * A big tournament wants this on paper — several copies taped around the bar —
 * and on a screen behind the bar. So it is a full page rather than a dialog:
 * one page prints as one sign, and the same page thrown on a TV is already the
 * right shape.
 *
 * Available from the moment the tournament is created, because `join_token` is
 * generated by the database on insert — the organizer can print signs before
 * anyone has shown up.
 *
 * The QR is forced to black-on-white rather than theme colours. It has to
 * survive being printed and being scanned across a dim room, and a themed QR in
 * dark mode is a black square on a dark card — unreadable both ways.
 */

import { Link, useParams } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useBracket } from '@/api/hooks/useBrackets';
import { hasPremiumFeature } from './premiumFeatures';
import { joinUrl } from './joinUrl';

export function JoinQrPoster() {
  const { bracketId } = useParams<{ bracketId: string }>();
  const { data, isLoading, isError } = useBracket(bracketId);

  if (isLoading) return <Centered>Loading…</Centered>;
  if (isError || !data) return <Centered>Tournament not found.</Centered>;

  const { bracket } = data;

  // The join link only means anything for a sign-up tournament.
  if (!hasPremiumFeature(bracket.premium_features, 'real_players') || !bracket.join_token) {
    return (
      <Centered>
        <p>This tournament doesn't use player sign-up, so it has no join code.</p>
        <Link to={`/brackets/${bracket.id}`} className="underline">
          Go to the tournament
        </Link>
      </Centered>
    );
  }

  const url = joinUrl(bracket.join_token);

  return (
    <div className="container mx-auto max-w-3xl px-4 py-6">
      {/* Chrome — deliberately absent from the printed sheet. */}
      <div className="mb-6 flex items-center justify-between gap-2 print:hidden">
        <Link
          to={`/brackets/${bracket.id}/setup`}
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Back to players
        </Link>
        <Button loadingText="none" onClick={() => window.print()}>
          <Printer className="mr-2 h-4 w-4" />
          Print
        </Button>
      </div>

      {/* The sign itself. White ground so it prints clean and scans in any theme. */}
      <div className="flex flex-col items-center gap-6 rounded-lg border bg-white px-6 py-10 text-center text-black">
        <div className="space-y-1">
          <p className="text-lg font-medium uppercase tracking-wide">Scan to join</p>
          <h1 className="text-4xl font-bold break-words">{bracket.name}</h1>
        </div>

        <QRCodeSVG
          value={url}
          size={512}
          level="M"
          fgColor="#000000"
          bgColor="#ffffff"
          includeMargin
          className="h-auto w-full max-w-sm"
        />

        <div className="space-y-2">
          <p className="text-base">
            Point your phone camera at the code, then sign in — you'll be added
            to the player list.
          </p>
          {/* For anyone whose camera won't cooperate. */}
          <p className="font-mono text-sm break-all">{url}</p>
        </div>
      </div>
    </div>
  );
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div className="container mx-auto max-w-2xl space-y-2 px-4 py-16 text-center text-muted-foreground">
      {children}
    </div>
  );
}
