import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';
import pkg from './package.json';

/**
 * Vitest config.
 *
 * Two projects so DB-backed tests (which share a single local Postgres
 * and would race each other under parallel execution) get pinned to
 * sequential execution automatically — neither the developer nor CI
 * has to remember a flag.
 *
 *   - unit       : every other *.test.* file. Parallel, happy-dom.
 *   - db         : src/__tests__/database/**. Sequential (fileParallelism:
 *                  false), jsdom (some files import supabase-js, which
 *                  happy-dom can't handle on writes).
 *
 * Run `pnpm test:run` to execute both projects; vitest handles the
 * sequential-vs-parallel scheduling per project transparently.
 */
export default defineConfig({
  // Mirrors the `define` in vite.config.ts. Without it `__APP_VERSION__` is
  // simply undefined under vitest, so ANY test that renders a component
  // referencing it dies with "__APP_VERSION__ is not defined" — which is why
  // WhatsNewPage had no render test until now. Kept in step with vite.config.ts.
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  plugins: [react()],
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        'src/test/',
        '**/*.d.ts',
        '**/*.config.*',
        '**/mockData',
        '**/.{idea,git,cache,output,temp}',
      ],
    },
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'happy-dom',
          setupFiles: ['./src/test/setup.ts'],
          // Anchored to `src/` so the unit project doesn't sweep into
          // sibling git worktrees (`.worktrees/<other-branch>/src/...`)
          // and run stale test files from unrelated branches. All real
          // test files live under `src/`; if that changes, widen this
          // include rather than reverting to a project-root glob.
          include: ['src/**/*.{test,spec}.{ts,tsx}'],
          exclude: [
            'node_modules',
            'dist',
            '.next',
            '.cache',
            '.worktrees/**',
            'src/__tests__/database/**',
          ],
        },
      },
      {
        extends: true,
        test: {
          name: 'db',
          globals: true,
          environment: 'jsdom',
          setupFiles: ['./src/test/setup.ts'],
          include: ['src/__tests__/database/**/*.{test,spec}.ts'],
          fileParallelism: false,
        },
      },
    ],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // `virtual:pwa-register/react` is generated by vite-plugin-pwa, which is
      // not in the vitest plugin chain — without this, any component importing
      // it fails to RESOLVE before vi.mock can intercept, so it can't be tested
      // at all. Points at an inert stub; tests still vi.mock the virtual id to
      // drive behaviour.
      'virtual:pwa-register/react': path.resolve(
        __dirname,
        './src/test/stubs/pwaRegister.ts'
      ),
    },
  },
});
