/**
 * @fileoverview The join URL for a room — the thing the QR encodes and the
 * link copies. One builder, so the two can never disagree.
 *
 * It is the sign-in funnel: `/rooms/join/:token` is a member route, so a
 * signed-out scanner is sent through login/register by `ProtectedRoute` and
 * redirected back here. Nothing about that lives in this file; it just has
 * to point at that route.
 */

/**
 * @param joinToken - `rooms.join_token`, generated by the database on insert.
 * @returns An absolute URL — it is encoded in a QR and read off a screen.
 */
export function roomJoinUrl(joinToken: string): string {
  return `${window.location.origin}/rooms/join/${joinToken}`;
}
