/**
 * @fileoverview Schedule-related type definitions
 *
 * Types for team schedule positions, matches, and schedule generation.
 * Used for creating and managing league schedules with matchup assignments.
 */

import type { SeasonWeek } from './season';

/**
 * Match status types
 */
export type MatchStatus =
  | 'scheduled'             // Not yet played
  | 'updating'              // LO is hand-entering this match (manual scoring); off the players' live surfaces
  | 'in_progress'           // Currently being played
  | 'awaiting_verification' // Scored but needs both teams to verify
  | 'completed'             // Finished and verified
  | 'forfeited'             // One team forfeited
  | 'postponed';            // Rescheduled to different date

/**
 * Team schedule position assignment
 * Maps teams to positions (1-N) used in matchup tables
 */
export interface TeamSchedulePosition {
  id: string;
  season_id: string;
  team_id: string;
  schedule_position: number;  // 1-N position in matchup table
  created_at: string;
  updated_at: string;
}

/**
 * Team schedule position insert data
 * Uses Omit<> to exclude auto-generated fields
 * This automatically stays in sync when TeamSchedulePosition type changes
 */
export type TeamSchedulePositionInsertData = Omit<TeamSchedulePosition,
  | 'id'          // Auto-generated by database
  | 'created_at'  // Auto-generated timestamp
  | 'updated_at'  // Auto-generated timestamp
>;

/**
 * Match record - weekly matchup between two teams
 */
export interface Match {
  id: string;
  season_id: string;
  season_week_id: string;       // FK to season_weeks table
  // After PR 1 of the team-deletion-cascade fix, byes are real teams rows
  // (status='bye'), so new matches always have non-null UUIDs here. NULL
  // remains in the type for legacy matches predating the NULL-bye backfill
  // migration; defensive consumers should treat NULL as a stale bye and
  // handle it the same as opponent.status === 'bye'.
  home_team_id: string | null;
  away_team_id: string | null;
  scheduled_venue_id: string | null;  // Home team's venue by default
  actual_venue_id: string | null;     // If venue changed from scheduled (overflow)
  assigned_table_number: number | null; // Table number assigned at the venue
  match_number: number;          // Order on the night (1, 2, 3...)
  status: MatchStatus;

  // Running totals (updated by per-game scoring mutation in Phase 5 Unit 5.5).
  // Per the v2 plan, the redundant home_team_score / away_team_score columns
  // are dropped — they silently mirrored either home_games_won (BCA) or
  // home_points_earned (Fargo) depending on league type. Display layer reads
  // the right one based on win_condition from the snapshot.
  home_games_won: number | null;
  away_games_won: number | null;
  home_points_earned: number | null;
  away_points_earned: number | null;

  // Threshold values (mode-neutral names; meaning depends on win_condition).
  // games-mode: target/tie/lose game counts. points-mode: points-target /
  // start-points-credit / NULL. See ResolvedSystemConfig for unit context.
  home_to_win: number | null;
  home_to_tie: number | null;
  home_to_lose: number | null;
  away_to_win: number | null;
  away_to_tie: number | null;
  away_to_lose: number | null;

  // Set when the match is completed. Kept on a v2 LO reopen (the correction
  // flow flips status to 'updating' but preserves completion fields), so
  // `status === 'updating' && completed_at != null` means "a finished match is
  // being corrected" vs a fresh manual entry (`updating`, completed_at null).
  completed_at: string | null;

  created_at: string;
  updated_at: string;
}

/**
 * Match insert data
 * Uses Omit<> to exclude auto-generated fields and nullable score fields
 * This automatically stays in sync when Match type changes
 */
export type MatchInsertData = Omit<Match,
  | 'id'                     // Auto-generated by database
  | 'actual_venue_id'        // Set later if venue changes (overflow)
  | 'assigned_table_number'  // Assigned by trigger/function
  | 'home_games_won'         // Filled during match scoring
  | 'away_games_won'         // Filled during match scoring
  | 'home_points_earned'     // Filled during match scoring
  | 'away_points_earned'     // Filled during match scoring
  | 'home_to_win'            // Set at match prep
  | 'home_to_tie'            // Set at match prep
  | 'home_to_lose'           // Set at match prep
  | 'away_to_win'            // Set at match prep
  | 'away_to_tie'            // Set at match prep
  | 'away_to_lose'           // Set at match prep
  | 'completed_at'           // Set when the match completes
  | 'created_at'             // Auto-generated timestamp
  | 'updated_at'             // Auto-generated timestamp
>;

/**
 * Match with expanded team and venue details
 * Used for displaying match information
 */
export interface MatchWithDetails extends Match {
  scheduled_date?: string;  // Denormalized from season_week for easier access
  home_team?: {
    id: string;
    team_name: string;
    captain_id: string | null;
    status: 'active' | 'withdrawn' | 'forfeited' | 'bye';
  } | null;
  away_team?: {
    id: string;
    team_name: string;
    captain_id: string | null;
    status: 'active' | 'withdrawn' | 'forfeited' | 'bye';
  } | null;
  scheduled_venue?: {
    id: string;
    name: string;
    street_address?: string;
    city: string;
    state: string;
  } | null;
  actual_venue?: {
    id: string;
    name: string;
    street_address?: string;
    city: string;
    state: string;
  } | null;
  season_week?: {
    id: string;
    scheduled_date: string;
    week_name: string;
    week_type: string;
  } | null;
}

/**
 * Matchup pair from matchup tables
 * Array of [position1, position2] representing which teams play
 */
export type MatchupPair = [number, number];

/**
 * Weekly matchup structure from matchup tables (legacy format)
 * @deprecated Use optimized format (MatchupPair[][]) for new schedules
 */
export interface WeeklyMatchup {
  week: number;
  matches: MatchupPair[];
}

/**
 * Matchup table type - array of weeks, each containing match pairs
 * Week number = array index + 1
 */
export type MatchupTable = MatchupPair[][];

/**
 * Team with assigned schedule position
 * Used during schedule generation
 */
export interface TeamWithPosition {
  id: string;
  team_name: string;
  home_venue_id: string | null;
  schedule_position: number;
}

/**
 * Note: SeasonWeek is imported from season.ts (see top of file)
 * This avoids type duplication - the complete definition is in season.ts
 */

/**
 * Extended match details with venue location
 */
export interface MatchWithVenueDetails extends MatchWithDetails {
  scheduled_venue?: {
    id: string;
    name: string;
    street_address: string;
    city: string;
    state: string;
  } | null;
}

/**
 * Week schedule data - week with all its matches
 */
export interface WeekSchedule {
  week: SeasonWeek;
  matches: MatchWithDetails[];
}
