// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "4-1",
    game: "10-ball",
    heading: "The Game",
    body: [
      "10-Ball is a call shot game played with a cue ball and ten object balls numbered 1 through 10.",
      "You shoot the balls in ascending numerical order.",
      "The 10-ball is the game winning ball.",
      "The object of the game is to pocket the 10-ball on any legal shot after the break. The game is played by two players or two teams.",
    ],
    order: 0,
  },
  {
    id: "4-2",
    game: "10-ball",
    heading: "10-Ball Rack",
    body: [
      "The balls are racked as follows (see Figure 4-1):",
      "a. in a triangle shape with the 1-ball as the apex ball on the foot spot (AR p. 84);",
      "b. the rows behind the apex are parallel to the foot string;",
      "c. the 10-ball is in the middle of the row of three balls;",
      "d. the 2-ball and 3-ball are placed on the ends of the last row (left/right orientation does not matter);",
      "e. the remaining balls are placed at random.",
    ],
    order: 1,
  },
  {
    id: "4-3",
    game: "10-ball",
    heading: "Break Requirements",
    body: [
      "1. You begin the break with ball in hand behind the head string. The break is not a called shot, and you may not call a ball on the break. The cue ball must contact the 1-ball before any other ball or cushion, or it is a foul. You must either legally pocket a ball or cause at least four object balls to contact one or more cushions, or it is a foul. 2. If you legally pocket a ball, you continue to shoot. Your inning ends if you do not legally pocket a ball or if you foul.",
      "3. If you legally pocket the 10-ball on the break, it is spotted and your inning continues.",
      "4. Jumped object balls other than the 10-ball are not returned to the table. If the 10-ball is jumped, it is spotted.",
    ],
    order: 2,
  },
  {
    id: "4-4",
    game: "10-ball",
    heading: "Push-out After the Break",
    body: [
      "1. If there was no foul on the break, the player taking the first shot after the break has the option to shoot a push-out. On a push-out:",
      "a. you must notify your opponent before the shot and your opponent must acknowledge your intention;",
      "b. the cue ball is not required to contact the lowest numbered ball first, or any object ball at all;",
      "c. no ball is required to contact a cushion",
      "d. all other rules and fouls still apply.",
      "2. Any object balls except the 10-ball that are pocketed on a push-out remain pocketed. If the 10-ball is pocketed it is spotted.",
      "3. After a push-out without a foul, your opponent may:",
      "c. accept the table in position and shoot;",
      "d. require you to shoot again with the table in position. If you push-out and foul, your opponent receives ball in hand.",
    ],
    order: 3,
  },
  {
    id: "4-5",
    game: "10-ball",
    heading: "Continuing Play",
    body: [
      "1. After the break (and push-out, if one occurs), play continues as follows:",
      "a. you must contact the lowest numbered ball on the table first or it is a foul;",
      "b. the 10-ball is spotted if it is illegally pocketed or if it is jumped;",
      "c. other jumped object balls and illegally pocketed balls are not spotted.",
      "2. When it is your inning, you continue to shoot as long as you legally pocket a called ball on each shot. If the called ball is legally pocketed, object balls, other than the 10- ball, pocketed in addition to the called ball remain pocketed. If the 10 ball is pocketed in addition to the called ball, it is spotted. Your inning ends if you do not legally pocket a ball. (AR p. 103)",
      "3. The game is won by the player who legally pockets the 10-ball.",
    ],
    order: 4,
  },
  {
    id: "4-6",
    game: "10-ball",
    heading: "(Reserved for future use)",
    body: [

    ],
    order: 5,
  },
  {
    id: "4-7",
    game: "10-ball",
    heading: "Illegally Pocketed Balls",
    body: [
      "1. A ball is illegally pocketed if it is:",
      "a. the called ball and is pocketed in other than the called pocket;",
      "b. not the called ball and is pocketed on a shot in which the called ball is not legally pocketed;",
      "2. If the 10-ball is illegally pocketed it is spotted. All other illegally pocketed balls remain pocketed.",
    ],
    order: 6,
  },
  {
    id: "4-8",
    game: "10-ball",
    heading: "Opponent's Option",
    body: [
      "If you illegally pocket any ball, your opponent has the option to:",
      "a. accept the table in position, or;",
      "b. require you to shoot again.",
    ],
    order: 7,
  },
  {
    id: "4-9",
    game: "10-ball",
    heading: "Three Successive Fouls",
    body: [
      "You lose the game if you commit three successive fouls in one game.",
    ],
    order: 8,
  },
  {
    id: "4-10",
    game: "10-ball",
    heading: "Stalemate",
    body: [
      "If a referee judges that the game is not progressing because the position of the table has not significantly changed through three consecutive innings by each player, the referee will declare a stalemate and the game will be replayed with the player who broke the game breaking again. (AR p. 104)",
      "Target pockets",
    ],
    order: 9,
  },
];
export default rules;
