// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "6-1",
    game: "14-1-continuous",
    heading: "The Game",
    body: [
      "14.1 Continuous (also referred to as “Straight Pool”) is a call shot game played with a cue ball and fifteen object balls numbered 1 through 15.",
      "You are allowed to pocket the first 14 balls of the rack, but before shooting the 15 th",
      "ball the 14 previously pocketed balls are racked, leaving the apex space vacant. After the 14 balls have been racked, you continue to shoot by attempting to pocket the 15 th",
      "ball while simultaneously breaking out some of the 14 racked balls so your run may continue.",
      "The object of the game is to score a predetermined point total before your opponent. The game is played by two players or two teams.",
    ],
    order: 0,
  },
  {
    id: "6-2",
    game: "14-1-continuous",
    heading: "The Rack",
    body: [
      "For the opening break, the balls are racked as follows (see Figure 6-1):",
      "a. in a triangle with the apex ball on the foot spot (AR p. 84);",
      "b. the rows behind the apex are parallel to the foot string;",
      "c. on the row at the rear of the rack the 1-ball must be on the corner to your right and the 5-ball must be on the corner to your left;",
      "d. all other balls are placed randomly.",
    ],
    order: 1,
  },
  {
    id: "6-3",
    game: "14-1-continuous",
    heading: "Opening Break Requirements",
    body: [
      "1. You begin the opening break with cue ball in hand behind the head string. You must:",
      "a. pocket a called ball in a called pocket or;",
      "b. cause the cue ball to contact an object ball and, after that contact, cause the cue ball and at least two object balls to contact one or more cushions. 2. Failure to meet the opening break requirement is an opening break violation.",
    ],
    order: 2,
  },
  {
    id: "6-4",
    game: "14-1-continuous",
    heading: "Opening Break Violation – Penalty",
    body: [
      "1. If you commit an opening break violation, you are penalized 2 points. Your opponent may:",
      "a. accept the table in position, or;",
      "b. require you to re-rack all 15 balls and repeat the opening break. This procedure continues until you meet the opening break requirement or your opponent accepts the table in position.",
      "2. An opening break violation does not count as a foul under the Successive Foul Penalty rule.",
    ],
    order: 3,
  },
  {
    id: "6-5",
    game: "14-1-continuous",
    heading: "Scratch or Foul on Opening Break - Penalty",
    body: [
      "If you meet the opening break requirement and scratch or foul, it is a one-point penalty. Any pocketed balls are spotted.",
      "If you scratch or the cue ball is jumped, your opponent receives cue ball in hand behind the head string with the object balls in position.",
      "If you commit a foul other than a scratch or jumped cue ball, your opponent accepts the table in position. The foul counts as the first foul under the Successive Foul Penalty rule.",
    ],
    order: 4,
  },
  {
    id: "6-6",
    game: "14-1-continuous",
    heading: "Scratch or Foul and Opening Break Violation - Penalty",
    body: [
      "1. If you scratch or foul on the opening break and fail to meet the opening break requirement, you are penalized 2 points. Your opponent may:",
      "a. take cue ball in hand behind the head string with the table in position, or;",
      "b. require you to re-rack all 15 balls and repeat the opening break.",
      "2. This situation is penalized as an opening break violation only. You are penalized two points, but the violation does not count as a foul under the Successive Foul Penalty Rule.",
    ],
    order: 5,
  },
  {
    id: "6-7",
    game: "14-1-continuous",
    heading: "Continuing Play",
    body: [
      "All object balls are legal.",
      "Legally pocketing a ball entitles you to continue your inning. Your inning ends if you do not legally pocket a ball.",
    ],
    order: 6,
  },
  {
    id: "6-8",
    game: "14-1-continuous",
    heading: "Subsequent Racks",
    body: [
      "After you pocket the 14 th",
      "ball of a rack, play stops temporarily while you rack the previously pocketed 14 balls. You rack the balls as before, but with the apex (foot spot) vacant and all balls placed randomly.",
      "Your inning then continues. You are not required to shoot at the 15 th",
      "ball. (AR p. 104)",
    ],
    order: 7,
  },
  {
    id: "6-9",
    game: "14-1-continuous",
    heading: "Subsequent Racks - Position and Placement of Cue Ball and 15 th",
    body: [
      "Object",
      "Ball",
      "When you prepare subsequent racks, the positions of the cue ball and the 15 th",
      "object ball determine their placement.",
      "object ball in situations where one or both are in the rack or interfere with the lowering of the triangle or spotting.",
    ],
    order: 8,
  },
  {
    id: "6-10",
    game: "14-1-continuous",
    heading: "Illegally Pocketed Ball",
    body: [
      "All illegally pocketed balls are spotted. There is no penalty for illegally pocketing a ball. Balls pocketed on a safety are illegally pocketed balls. (AR p. 101)",
    ],
    order: 9,
  },
  {
    id: "6-11",
    game: "14-1-continuous",
    heading: "Safety Play",
    body: [
      "You may declare a safety at any time during your inning. It is a foul if a safety shot does not meet the requirements of a legal shot. Any object ball pocketed on a safety is spotted. The safety play ends your inning.",
    ],
    order: 10,
  },
  {
    id: "6-12",
    game: "14-1-continuous",
    heading: "Scoring",
    body: [
      "1. Keeping score requires you to maintain two separate tallies – a tally for each rack and a running total score for the game. As each individual rack is played, you keep a tally for that rack. At the conclusion of the rack, your individual rack tally is added to your game score, and your rack tally resets to zero prior to beginning the subsequent rack.",
      "2. A legally pocketed ball counts as one point. Any object balls pocketed in addition to Cue ball lies 15th ball lies In the rack or interfering with lowering the triangle Not in the rack or on the head spot On the head spot or interfering with spotting a ball on head spot In the rack or interfering with lowering the triangle 15th ball: foot spot. Cue ball: in the kitchen 15th ball: head spot. Cue ball: in position 15th ball: center spot. Cue ball: in position Pocketed 15th ball: foot spot Cue ball: in position In the kitchen but not on head the spot 15th ball: in position. Cue ball: head spot INTERFERENCE BALLS REMAIN IN POSITION Not in the kitchen or the rack 15th ball: in position. Cue ball: in the kitchen On the head spot or interfering with spotting a ball on the head spot 15th ball: in position. Cue ball: center spot",
    ],
    order: 11,
  },
  {
    id: "6-13",
    game: "14-1-continuous",
    heading: "Foul Penalty",
    body: [
      "One point is deducted for each shot in which a foul occurs.",
      "Your opponent accepts the cue ball in position unless the foul was the result of a scratch, jumped cue ball, deliberate foul or third successive foul.",
    ],
    order: 12,
  },
  {
    id: "6-14",
    game: "14-1-continuous",
    heading: "Deducting Points",
    body: [
      "If you foul but do not pocket a ball, the penalty for the foul is deducted from your running game total. If you foul and pocket a ball on the same shot, the ball is spotted, it is not scored, and the penalty for the foul is deducted from your running game total. The deduction of penalty points can result in a negative score.",
    ],
    order: 13,
  },
  {
    id: "6-15",
    game: "14-1-continuous",
    heading: "Scratch or Cue Ball Jumped Off Table",
    body: [
      "A scratch or jumped cue ball is a foul.",
      "Your opponent receives ball in hand behind the head string.",
    ],
    order: 14,
  },
  {
    id: "6-16",
    game: "14-1-continuous",
    heading: "Object Ball Jumped Off Table",
    body: [
      "A jumped object ball is a foul. The jumped ball is spotted and your opponent accepts the cue ball in position.",
    ],
    order: 15,
  },
  {
    id: "6-17",
    game: "14-1-continuous",
    heading: "Deliberate Foul – Special Penalty",
    body: [
      "1. If you violate Rule 1-40, you are penalized one point for the foul and an additional fifteen points for the deliberate act, for a total of sixteen points. Your opponent may:",
      "a. accept the table in position;",
      "b. take cue ball in hand behind the head string with the object balls in position, or;",
      "c. require you to re-rack all 15 balls and repeat the opening break.",
      "2. A deliberate foul does not count as a foul under the Successive Foul Penalty (Rule 1- 22), nor does it reset the successive foul count, if any.",
    ],
    order: 16,
  },
  {
    id: "6-18",
    game: "14-1-continuous",
    heading: "Three Successive Fouls Penalty",
    body: [
      "1. If you commit a third successive foul:",
      "a. you are penalized the appropriate point penalty for the foul plus an additional 15 point penalty;",
      "b. you must re-rack all 15 balls and meet the opening break requirement;",
      "c. the points scored in the rack up to that point are added to the running totals, and the tallies for a new rack begin.",
    ],
    order: 17,
  },
  {
    id: "6-19",
    game: "14-1-continuous",
    heading: "Jump Shot Requirement",
    body: [
      "Jump shots may only be attempted with your playing cue.",
    ],
    order: 18,
  },
  {
    id: "6-20",
    game: "14-1-continuous",
    heading: "All Remaining Balls Behind the Head String with Cue",
    body: [
      "Ball in Hand Behind the Head String",
      "When you have cue ball in hand behind the head string and all of the remaining object balls are also behind the head string, the object ball nearest the head string may be spotted upon your request. If two or more balls at an equal distance from the head string are nearest the head string, you may choose which ball to spot.",
    ],
    order: 19,
  },
  {
    id: "6-21",
    game: "14-1-continuous",
    heading: "Stalemate",
    body: [
      "1. If a referee judges that the table is in a position such that no progress is being made toward a conclusion, they will announce their decision and each player will play three more innings. After that, if the referee determines there is still no progress they will declare a stalemate.",
      "2. If a stalemate is declared, all 15 balls will be racked and the players will lag to determine who will shoot the opening break. The points scored in the stalemated rack are counted and are added to the running total scores and the tallies for a new rack begin. (AR p. 103, 104) Long rack – full triangle Short rack – shaded area only",
    ],
    order: 20,
  },
];
export default rules;
