// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "2-1",
    game: "8-ball",
    heading: "The Game",
    body: [
      "8-Ball is a call shot game played with a cue ball and fifteen object balls numbered 1 through 15.",
      "Each player or team has a group of seven balls: the solid colored balls numbered 1 through 7, or the striped balls numbered 9 through 15.",
      "The 8-ball is the game winning ball.",
      "The object of the game is to pocket your entire group of balls and then legally pocket the 8-ball. The game is played by two players or two teams.",
    ],
    order: 0,
  },
  {
    id: "2-2",
    game: "8-ball",
    heading: "8-Ball Rack",
    body: [
      "The balls are racked as follows (see Figure 2-1):",
      "a. in a triangle with the apex ball on the foot spot (AR p. 84);",
      "b. the rows behind the apex are parallel to the foot string;",
      "c. the 8-ball is in the middle of the row of three balls;",
      "d. the remaining balls are placed at random, except that the ball at each rear corner of the rack must be of a different group from the other rear corner (the left/right orientation those two balls does not matter). (AR p. 102)",
    ],
    order: 1,
  },
  {
    id: "2-3",
    game: "8-ball",
    heading: "Break Requirements",
    body: [
      "1. You begin the break with ball in hand behind the head string. The break is not a called shot, and you may not call a ball or a safety on the break. There is no requirement for the cue ball to contact any particular ball first. You must legally pocket a ball or cause at least four object balls to contact one or more cushions or it is an illegal break. If you legally pocket a ball, you continue to shoot. If you do not legally pocket a ball or you commit a foul, your inning ends. (AR p. 102) 2. If you intend to break softly, you must notify your opponent and allow them the opportunity to call a referee to watch your break. If you fail to notify your opponent you will receive a mandatory warning on the first offense. Second and subsequent offenses are fouls.",
      "3. If your break is illegal, with or without a foul, your inning ends. Your opponent may:",
      "a. re-rack the balls and break;",
      "b. require you to re-rack the balls and break again; The game cannot continue until there is a legal break. If your opponent’s break is illegal and there is also a foul, the illegal break takes precedence and you must choose either option (a) or (b) above.",
      "4. If you foul on a legal break and do not pocket the 8-ball, your inning ends and any other pocketed object balls remain pocketed. Your opponent receives ball in hand anywhere on the table.",
      "5. In all cases on the break, jumped object balls other than the 8-ball are not returned to the table except in the case of a re-rack. If the 8-ball is jumped it is spotted.",
    ],
    order: 2,
  },
  {
    id: "2-4",
    game: "8-ball",
    heading: "8-Ball Pocketed on the Break",
    body: [
      "(AR p. 102)",
      "1. If you pocket the 8-ball on the break and do not foul, you may:",
      "a. have the 8-ball spotted and accept the table in position;",
      "b. re-rack the balls and break again.",
      "2. If you pocket the 8-ball on the break and foul, your inning ends. Your opponent may:",
      "a. have the 8-ball spotted and take ball in hand anywhere on the table;",
      "b. re-rack the balls and break.",
      "3. If the 8-ball is pocketed on the break, and it is not noticed until after another shot has been taken, the game will be replayed with the player who broke the game breaking again.",
    ],
    order: 3,
  },
  {
    id: "2-5",
    game: "8-ball",
    heading: "Table Open After the Break",
    body: [
      "The table is always open on the shot after the break and remains open until groups are established.",
      "When the table is open, all object balls except the 8-ball are legal object balls. For combination shots, a ball of one group may be contacted first to pocket a ball of the other group. The 8-ball may be part of such a combination if it is not the first ball contacted by the cue ball.",
    ],
    order: 4,
  },
  {
    id: "2-6",
    game: "8-ball",
    heading: "Establishing Groups",
    body: [
      "1. Groups are established when the first object ball is legally pocketed on a shot after the break. The player legally pocketing the first ball is assigned that group, and the opponent is assigned the other group. You cannot establish a group on a safety. (AR p. 102)",
      "2. If all balls of either group are pocketed on the break or illegally pocketed before groups are established, either player may legally shoot the 8-ball during their inning. You win the game if you legally pocket the 8-ball on such a shot.",
      "3. Once they are established, groups can never change for the remainder of that game. If a player shoots the wrong group and no foul is called before the next shot and the player continues to shoot at that group, or if at any time during the game it is discovered by either player or a referee that the players are shooting the wrong groups, the game will be replayed with the player who broke the game breaking again. If a game has ended and then the players realize they shot the wrong groups, the game is not replayed and the result stands.",
    ],
    order: 5,
  },
  {
    id: "2-7",
    game: "8-ball",
    heading: "Continuing Play",
    body: [
      "1. Once groups are established, play continues with each player having their group as legal object balls. Balls in your opponents' group and the 8-ball are illegal object balls. When it is your inning, you continue to shoot as long as you legally pocket a ball on each shot. Object balls pocketed in addition to the called ball remain pocketed. Your inning ends if you do not legally pocket a ball.",
      "2. Jumped object balls and illegally pocketed balls are not returned to the table but do count in favor of the player with that group.",
    ],
    order: 6,
  },
  {
    id: "2-8",
    game: "8-ball",
    heading: "Safety Play",
    body: [
      "Prior to any shot except the break, you may declare a safety.",
      "On a safety, your inning ends after the shot regardless of whether you pocket any ball.",
      "If you do not declare a safety and you pocket a ball on an obvious shot, your inning continues and you must shoot again. A safety must meet the requirements of Rule 1.19, Legal Shot, or it is a foul. (AR p. 77, 103)",
    ],
    order: 7,
  },
  {
    id: "2-9",
    game: "8-ball",
    heading: "Shooting the 8-Ball",
    body: [
      "1. The 8-ball becomes your legal object ball on your first shot after there are no balls of your group on the table. The player who legally pockets the 8-ball wins the game. (AR p. 103)",
      "2. With the exception of the provisions of Rule 2.10, it is not loss of game if you foul when shooting the 8-ball but do not pocket the 8-ball. Your opponent receives ball in hand.",
    ],
    order: 8,
  },
  {
    id: "2-10",
    game: "8-ball",
    heading: "Loss of Game",
    body: [
      "You lose the game if:",
      "a. you illegally pocket the 8-ball; (AR p. 103)",
      "b. you jump the 8-ball off the table on any shot other than the break;",
      "c. you pocket the 8-ball on the same shot as the last ball of your group;",
      "d. you violate any General Rule that requires loss of game as a penalty;",
      "e. you pocket the 8-ball on a shot defined as not obvious that you do not call (Rule 1-16-6 does not apply to 8-Ball);",
      "f. you commit a foul under Rule 1-33-4 or 1-33-7 and the 8-ball falls into a pocket.",
    ],
    order: 9,
  },
  {
    id: "2-11",
    game: "8-ball",
    heading: "Stalemate",
    body: [
      "If a referee judges that the table is in a position such that any attempt to pocket or move a ball will result in loss of game on that shot, or that the game is not progressing because the position of the table has not significantly changed through three consecutive innings by each player, the referee will declare a stalemate and the game will be replayed with the player who broke the game breaking again. (AR p. 104)",
    ],
    order: 10,
  },
];
export default rules;
