// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "3-1",
    game: "9-ball",
    heading: "The Game",
    body: [
      "9-Ball is played with a cue ball and nine object balls numbered 1 through 9.",
      "You shoot the balls in ascending numerical order, continuing to shoot as long as any ball is legally pocketed.",
      "The 9-ball is the game-winning ball.",
      "The object of the game is to pocket the 9-ball on any legal shot. The game is played by two players or two teams.",
    ],
    order: 0,
  },
  {
    id: "3-2",
    game: "9-ball",
    heading: "9-Ball Rack",
    body: [
      "The balls are racked as follows (see Figure 3-1):",
      "a. in a diamond shape with the 1-ball as the apex ball on the foot spot (AR p. 84);",
      "b. the rows behind the apex are parallel to the foot string;",
      "c. the 9-ball is in the middle of the rack;",
      "d. the remaining balls are placed at random.",
    ],
    order: 1,
  },
  {
    id: "3-3",
    game: "9-ball",
    heading: "Break Requirements",
    body: [
      "1. You begin the break with ball in hand behind the head string. The cue ball must contact the 1-ball before any other ball or cushion or it is a foul. You must either legally pocket a ball or cause at least four object balls to contact one or more cushions, or it is a foul.",
      "2. Jumped object balls other than the 9-ball are not returned to the table. If the 9-ball is jumped, it is spotted.",
      "3. If you legally pocket a ball, you continue to shoot. Your inning ends if you do not pocket a ball or if you foul. If you legally pocket the 9-ball on the break, you win the game. If you foul on the break and pocket the 9-ball, it is spotted.",
    ],
    order: 2,
  },
  {
    id: "3-4",
    game: "9-ball",
    heading: "Push-out After the Break",
    body: [
      "1. If there was no foul on the break, the player taking the first shot after the break has the option to shoot a push-out. On a push-out:",
      "a. you must notify your opponent before the shot and your opponent must acknowledge your intention;",
      "b. the cue ball does not have to contact the lowest numbered ball first, or any object ball at all;",
      "c. no ball has to contact a cushion",
      "d. all other rules and fouls still apply.",
      "2. Any object balls except the 9-ball that are pocketed on a push-out remain pocketed. If the 9-ball is pocketed it is spotted.",
      "3. After a push-out without a foul, your opponent may:",
      "a. accept the table in position and shoot;",
      "b. require you to shoot again with the table in position. If you push-out and foul, your opponent receives ball in hand.",
    ],
    order: 3,
  },
  {
    id: "3-5",
    game: "9-ball",
    heading: "Continuing Play",
    body: [
      "1. After the break (and push-out, if one occurs), play continues as follows:",
      "a. the lowest numbered ball on the table must be the first object ball contacted by the cue ball or it is a foul;",
      "b. if you legally pocket any ball your inning must continue;",
      "c. the 9-ball is spotted if it is illegally pocketed or if it is jumped (AR p. 103);",
      "d. other jumped object balls and illegally pocketed balls are not returned to the table.",
      "2. When it is your inning, you must continue to shoot as long as you legally pocket a ball on each shot. Your inning ends if you do not legally pocket a ball.",
      "3. The game is won by the player who legally pockets the 9-ball.",
    ],
    order: 4,
  },
  {
    id: "3-6",
    game: "9-ball",
    heading: "Three Successive Fouls",
    body: [
      "You lose the game if you commit three successive fouls in one game.",
    ],
    order: 5,
  },
  {
    id: "3-7",
    game: "9-ball",
    heading: "Stalemate",
    body: [
      "If a referee judges that the game is not progressing because the position of the table has not significantly changed through three consecutive innings by each player, the referee will declare a stalemate and the game will be replayed with the player who broke the game breaking again. (AR p. 103)",
    ],
    order: 6,
  },
];
export default rules;
