// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "7-1",
    game: "bank-pool",
    heading: "The Game",
    body: [
      "1. Bank Pool (also called “Banks”) is a call shot game played with fifteen object balls, numbered 1 through 15, plus a cue ball in the long rack game, and any nine object balls plus a cue ball in the short rack game. To score you are required to play a bank shot. The object of the game is to score a predetermined number of balls before your opponent does. The game is played by two, three, four or five players. Two players may play either a long rack or short rack game. For three, four or five players, the long rack game is the suggested format.",
    ],
    order: 0,
  },
  {
    id: "7-2",
    game: "bank-pool",
    heading: "The Rack",
    body: [
      "The balls are racked as follows (see Figure 7-1):",
      "a. in long rack bank pool, in a triangle and placed randomly;",
      "b. in short rack bank pool, in a diamond (shaded area in Figure 7-1) and placed randomly;",
      "c. the apex ball on the foot spot (AR p. 84);",
      "d. the rows behind the apex are parallel to the foot string.",
    ],
    order: 1,
  },
  {
    id: "7-3",
    game: "bank-pool",
    heading: "Break Requirements",
    body: [
      "1. You begin the break with cue ball in hand behind the head string. There is no requirement to contact any particular object ball first. You must cause at least four object balls to contact the cushions or it is an illegal break. If any balls are pocketed on the opening break, you continue shooting. Any balls pocketed on the opening break are not scored and are spotted after your inning ends.",
      "2. If your break is illegal, your opponent may:",
      "a. accept the table in position, or; b. re-rack the balls and break.",
    ],
    order: 2,
  },
  {
    id: "7-4",
    game: "bank-pool",
    heading: "Breaking Subsequent Racks",
    body: [
      "If a match consists of multiple games, players must alternate breaking subsequent games.",
    ],
    order: 3,
  },
  {
    id: "7-5",
    game: "bank-pool",
    heading: "Continuing Play",
    body: [
      "All object balls are legal. Your inning continues as long as you legally pocket a ball. Your inning ends if you do not legally pocket a ball.",
    ],
    order: 4,
  },
  {
    id: "7-6",
    game: "bank-pool",
    heading: "Scoring",
    body: [
      "A legally pocketed ball counts as one ball.",
      "Any ball pocketed in addition to the called ball on the same shot does not count and is an illegally pocketed ball.",
    ],
    order: 5,
  },
  {
    id: "7-7",
    game: "bank-pool",
    heading: "Legally Pocketed Ball",
    body: [
      "1. A ball is legally pocketed if:",
      "a. it is pocketed as the result of a bank shot;",
      "b. the number of cushions are designated when calling the shot and only that number of cushions are contacted;",
      "c. it is not pocketed as a result of a kiss or carom;",
      "d. it is not contacted by the cue ball more than once.",
      "2. Contact with a cushion means that the called ball has made contact with a cushion designated as a part of the called bank shot. Incidental contact with a cushion as the object ball approaches the called pocket is not considered contacting an extra cushion that would disqualify a shot from being legal based on the number of called cushions.",
    ],
    order: 6,
  },
  {
    id: "7-8",
    game: "bank-pool",
    heading: "Illegally Pocketed Ball",
    body: [
      "A ball is illegally pocketed if the shot does not meet the requirements of Rule 7-6, if it is pocketed in addition to the called ball, or if a foul is committed on the shot.",
    ],
    order: 7,
  },
  {
    id: "7-9",
    game: "bank-pool",
    heading: "Jump Shot Requirement",
    body: [
      "Jump shots may only be attempted with your playing cue.",
    ],
    order: 8,
  },
  {
    id: "7-10",
    game: "bank-pool",
    heading: "Foul Penalty",
    body: [
      "1. For each foul you commit you must spot one of your previously scored balls, reducing your score by one. (AR p. 104)",
      "2. If you foul and have no previously scored object balls, you “owe” one for that foul and must spot balls after each scoring inning until all “owed balls” are eliminated. 3. Your opponent accepts the cue ball in position, unless there is a scratch or it is jumped off the table.",
    ],
    order: 9,
  },
  {
    id: "7-11",
    game: "bank-pool",
    heading: "Scratch or Cue Ball Jumped Off Table",
    body: [
      "It is a foul if you scratch or jump the cue ball off the table. Your opponent receives ball in hand behind the head string.",
    ],
    order: 10,
  },
  {
    id: "7-12",
    game: "bank-pool",
    heading: "Jumped Balls",
    body: [
      "It is a foul if you jump an object ball off the table.",
      "The object ball is spotted and your opponent accepts the cue ball in position.",
    ],
    order: 11,
  },
  {
    id: "7-13",
    game: "bank-pool",
    heading: "Illegally Pocketed Balls – Spotting Requirements",
    body: [
      "All illegally pocketed balls are spotted, but spotting is delayed until the shooter’s inning ends. If you score the last ball remaining on the table but have not yet won the game, any illegally pocketed balls being held for spotting are then spotted at once and your inning continues.",
    ],
    order: 12,
  },
  {
    id: "7-14",
    game: "bank-pool",
    heading: "Spotting Forgotten Balls",
    body: [
      "If both",
      "players",
      "agree,",
      "forgotten",
      "balls",
      "may be spotted",
      "any time after they are remembered.",
      "If either player objects to the earlier spotting then any owed balls are spotted after the end of the next player’s inning. However, if there are no balls left on the table",
      "game",
      "been",
      "won,",
      "then",
      "forgotten",
      "balls",
      "must",
      "spotted immediately.",
    ],
    order: 13,
  },
  {
    id: "7-15",
    game: "bank-pool",
    heading: "All Remaining Balls are Behind the Head String with Cue",
    body: [
      "Ball in Hand Behind the Head String",
      "When you have cue ball in hand behind the head string and all remaining balls are also behind the head string, the object ball nearest the head string may be spotted upon your request.",
      "If two or more balls at an equal distance from the head string are nearest the head string, you may choose which ball to spot.",
    ],
    order: 14,
  },
  {
    id: "7-16",
    game: "bank-pool",
    heading: "End of Game",
    body: [
      "1. For two players, the game ends when:",
      "a. in a long rack game, one player has legally pocketed eight balls and does not owe any balls;",
      "b. in a short rack game, one player has legally pocketed five balls and does not owe any balls.",
      "2. For three, four or five players, the long rack game ends when one player has legally pocketed five, four, or three balls, respectively, and does not owe any balls.",
    ],
    order: 15,
  },
];
export default rules;
