// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "5-1",
    game: "one-pocket",
    heading: "The Game",
    body: [
      "The game of One Pocket is played with a cue ball and fifteen object balls, numbered 1 through 15, using only the two pockets at the foot of the table for scoring (target pockets). You score by pocketing object balls in your designated pocket. You win the game if you score eight balls before your opponent does.",
      "The game is played by two players or two teams.",
    ],
    order: 0,
  },
  {
    id: "5-2",
    game: "one-pocket",
    heading: "The Rack",
    body: [
      "The balls are racked as follows (see Figure 5-1):",
      "a. in a triangle with the apex ball on the foot spot and all balls placed randomly (AR p. 84);",
      "b. the rows behind the apex are parallel to the foot string.",
    ],
    order: 1,
  },
  {
    id: "5-3",
    game: "one-pocket",
    heading: "Choice of Pocket",
    body: [
      "Before the opening break of each game, the player breaking must choose one of the corner pockets at the foot of the table as their target pocket for that game. Their opponent must then accept the other corner pocket at the foot of the table as their target pocket for that game.",
    ],
    order: 2,
  },
  {
    id: "5-4",
    game: "one-pocket",
    heading: "Break Requirements",
    body: [
      "1. You begin the opening break with cue ball in hand behind the head string. You must:",
      "a. legally pocket a ball in your target pocket, or",
      "b. cause the cue ball to contact a ball and, after that contact, cause at least one object ball or the cue ball to contact a cushion. 2. It is a foul if you do not meet the opening break requirements.",
    ],
    order: 3,
  },
  {
    id: "5-5",
    game: "one-pocket",
    heading: "Breaking Subsequent Games",
    body: [
      "If a match consists of multiple games, players must alternate breaking subsequent games.",
    ],
    order: 4,
  },
  {
    id: "5-6",
    game: "one-pocket",
    heading: "Continuing Play",
    body: [
      "All object balls are legal. You are not required to call ball and pocket. Legally pocketing a ball entitles you to continue your inning. Your inning ends if you do not legally pocket a ball in your target pocket.",
    ],
    order: 5,
  },
  {
    id: "5-7",
    game: "one-pocket",
    heading: "Illegally Pocketed Ball",
    body: [
      "A ball is illegally pocketed if it is pocketed in other than a target pocket, or if a foul is committed on the shot.",
      "Illegally pocketed balls are spotted, but spotting is delayed until the shooter’s inning ends.",
      "If you legally pocket the last ball remaining on the table but have not yet won the game, all illegally pocketed balls being held for spotting are then spotted at once and your inning continues.",
    ],
    order: 6,
  },
  {
    id: "5-8",
    game: "one-pocket",
    heading: "Scoring",
    body: [
      "A ball is legally pocketed if it is pocketed in a target pocket on a legal shot.",
      "a. a ball legally pocketed in your target pocket counts as one ball for you;",
      "b. if you foul, any ball pocketed in your target pocket on that shot does not count and must be spotted (AR p. 104);",
      "c. a ball pocketed by you in your opponent’s target pocket counts for your opponent;",
      "d. if you commit a foul other than a scratch or jumped cue ball, any ball pocketed in your opponent’s target pocket counts for your opponent;",
      "e. if you scratch or jump the cue ball off the table, any ball pocketed in your opponent’s target pocket does not count for your opponent and must be spotted.",
    ],
    order: 7,
  },
  {
    id: "5-9",
    game: "one-pocket",
    heading: "Foul Penalty",
    body: [
      "1. For each foul you commit you must spot one of your previously scored balls, reducing your score by one. (AR p.104)",
      "2. If you foul and have no previously scored object balls, you “owe one” for that foul and must spot balls after each scoring inning until all “owed balls” are eliminated.",
      "3. After a foul, your opponent accepts the table in position.",
    ],
    order: 8,
  },
  {
    id: "5-10",
    game: "one-pocket",
    heading: "Scratch or Jumped Cue Ball",
    body: [
      "It is a foul if you scratch or jump the cue ball off the table. Your opponent receives ball in hand behind the head string.",
    ],
    order: 9,
  },
  {
    id: "5-11",
    game: "one-pocket",
    heading: "Jumped Balls",
    body: [
      "It is a foul if you jump any object ball off the table.",
      "The jumped ball is spotted and you are penalized one ball. Your opponent accepts the cue ball in position.",
    ],
    order: 10,
  },
  {
    id: "5-12",
    game: "one-pocket",
    heading: "Deliberately Trapping or Wedging the Cue Ball",
    body: [
      "It is a foul if you use an illegal stroke to deliberately attempt to trap or wedge the cue ball in the jaw of a pocket.",
      "In addition to the one ball penalty for a foul, your opponent receives ball in hand behind the head string.",
    ],
    order: 11,
  },
  {
    id: "5-13",
    game: "one-pocket",
    heading: "Three Successive Fouls - Penalty",
    body: [
      "You lose the game if you commit three successive fouls in one game.",
    ],
    order: 12,
  },
  {
    id: "5-14",
    game: "one-pocket",
    heading: "Spotting Forgotten Balls",
    body: [
      "If both",
      "players",
      "agree,",
      "forgotten",
      "balls may be spotted",
      "any time after they are remembered.",
      "If either player objects to the earlier spotting, then any owed balls or illegally pocketed balls are spotted after the end of the next player’s inning. However, if the game has not ended and there are no balls left on the table, the forgotten balls must all be spotted immediately.",
    ],
    order: 13,
  },
  {
    id: "5-15",
    game: "one-pocket",
    heading: "Jump Shot Requirement",
    body: [
      "You may only use your playing cue to attempt jump shots.",
    ],
    order: 14,
  },
  {
    id: "5-16",
    game: "one-pocket",
    heading: "All Remaining Balls are Behind the Head String with Cue",
    body: [
      "Ball in Hand Behind the Head String",
      "When you have ball in hand behind the head string and all of the remaining object balls are also behind the head string, the object ball nearest the head string may be spotted upon your request.",
      "If two or more balls at an equal distance from the head string are nearest the head string, you may choose which ball to spot.",
    ],
    order: 15,
  },
  {
    id: "5-17",
    game: "one-pocket",
    heading: "End of Game",
    body: [
      "The game ends when one player or team has legally pocketed eight balls and does not “owe” any balls. If you pocket a ball that brings your opponent’s score to eight balls, you have lost the game unless you scratch or jump the cue ball off the table on the same stroke.",
    ],
    order: 16,
  },
];
export default rules;
