// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "9-1",
    game: "scotch-doubles",
    heading: "Breaking",
    body: [
      "1. When it is your team’s turn to break, either player may break. You may discuss the decision with your partner. You are not required to maintain the order of play from any preceding game . 2. In 8-Ball, if you pocket the 8-ball on a legal break, and do not foul, your partner must make the decision whether to spot the 8-ball and continue to shoot or re-rack and break again. If a re-rack is chosen the player who broke the original rack must break again. If you pocket the 8-ball on an illegal break the incoming player must make the decision whether to take the break or have the original breaker re-break. In either case, the decision may not be discussed between partners. All other game formats (9-Ball, 10-Ball, etc.) follow the specific game rules for after the break.",
    ],
    order: 0,
  },
  {
    id: "9-2",
    game: "scotch-doubles",
    heading: "Continuing Play",
    body: [
      "1. After the break, players on a team alternate shots during their inning. The order of play must be maintained between innings. If a player shoots out of turn it is a foul.",
      "2. In 9 & 10 Ball if either team plays a push-out shot after the break, the player that performed the push-out shot returns to the table to continue with the shot if the opposing team declines to take the the shot and returns the table to the team that shot the push-out shot. The push-out shot is not considered two separate shots but one shot with two parts.",
    ],
    order: 1,
  },
  {
    id: "9-3",
    game: "scotch-doubles",
    heading: "Coaching",
    body: [
      "1. During your inning, open communicat ion between partners is allowed.",
      "2. Communication/coaching cannot result in slower than normal play. As a general guide, there should be no more than 45 seconds between each shot. If a team consistently uses more than 45 seconds between shots, the opposing team may summon a referee to monitor the match and the referee may institute delayed progress rulings at any time.",
      "3. The non-shooting player is allowed to point at or touch the table while offering advice but may not touch any ball including the cue ball when it is \"ball in hand\" or mark the table in any way. Mostly what should be offer ed is verbal advice . . Any player on either team, regardless of whose turn at the table it is, may:",
      "a. call a foul;",
      "b. request a stoppage of play to summon a referee, or suggest that a referee be summoned;",
      "c. inquire whose turn it is;",
      "d. inquire what group they have.",
    ],
    order: 2,
  },
  {
    id: "9-4",
    game: "scotch-doubles",
    heading: "Time Outs",
    body: [
      "1. Each team is entitled to one five-minute time out per match. The time-out must be taken between games. It is a foul if a team member leaves the playing area without authorization during a game.",
    ],
    order: 3,
  },
];
export default rules;
