// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.
import type { Rule } from "../../rules/rulebook.types";

export const rules: Rule[] = [
  {
    id: "8-1",
    game: "wheelchair",
    heading: "Disability Classifications",
    body: [
      "To be eligible for a wheelchair event you must have a mobility-impaired disability requiring the use of a wheelchair. You may be required to provide a physician’s letter to establish your eligibility. CSI wheelchair play encompasses two disability classifications:",
      "a. Wheelchair players who meet the definition of minimal disability and are unable to make and sustain a functional bridge with their non-cueing hand.",
      "b. All other wheelchair players who meet the definition of minimal disability and are able to make and sustain a functional bridge with their non-cueing hand.",
    ],
    order: 0,
  },
  {
    id: "8-2",
    game: "wheelchair",
    heading: "Minimal Disability Defined",
    body: [
      "The BCAPL defines minimal disability as:",
      "a. Loss of limb above the ankle;",
      "b. Decrease of muscle strength in one lower limb of at least 30 points;",
      "c. Severe mobility problems comparable with handicaps described in Rule 8-1.",
    ],
    order: 1,
  },
  {
    id: "8-3",
    game: "wheelchair",
    heading: "Wheelchair Rules of Play",
    body: [
      "(AR p. 104)",
      "1. You must remain seated on the cushion or the seat of the wheelchair when playing a shot. You must have at least one cheek on the cushion or seat when you strike the cue ball.",
      "2. If you use a cushion, it must remain flat and cover the seat of the wheelchair evenly. The cushion cannot be bunched up on the seat or be straddled by your legs or stumps. You may not sit on the wheel or armrest. The point where your buttocks rest on the seat or cushion must not be higher than 27 inches from the surface on which the wheelchair rolls in its normal operating position.",
      "3. Your feet must be kept clear of the floor. Your feet or footplates must not touch the floor when you strike the cue ball. You must not use your legs or stumps as leverage against any part of the table or wheelchair while shooting. It is a foul if you violate any of the provisions of Rule 8-3-1 through 3.",
      "4. If you have a classification 8-1-a disability, you may request the referee to assist you with your equipment. You may use any help aids such as cue extensions, special bridges, etc. You may not be assisted when actually shooting. However, another person may hold the bridge but must not help with the actual stroke. If you require assistance to roll around the table, another person may help but must not be touching the wheelchair during the actual shot. 5. Below-the-knee strapping is permitted to keep your feet on the footplates.",
      "6. Strapping above the waist is not permitted except for medical reasons.",
      "7. You may not use a standing wheelchair in the standing position.",
    ],
    order: 2,
  },
];
export default rules;
