/**
 * @fileoverview Emit the cleaned rulebook as committable TypeScript modules.
 *
 * We write TypeScript (not JSON) so the reader + future AI helper can import
 * typed data without touching `tsconfig.app.json`'s `resolveJsonModule` flag.
 * Each game section becomes a module that default-exports a `Rule[]`. A sibling
 * `index.ts` default-exports the `RulebookIndex` metadata plus the global
 * `(game, ruleId)` lookup map.
 *
 * Files go under `src/officalBCARulebook/cleaned/`. Existing files there are
 * overwritten on each run — the cleaned output is a deterministic artifact of
 * the source PDF, not hand-edited content.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Rule, RulebookIndex } from '../../src/rules/rulebook.types';
import type { GameMeta } from './games';

/** Where the cleaned modules land, relative to the repo root. */
const OUTPUT_DIR = 'src/officalBCARulebook/cleaned';

/** Path to the rulebook.types module, written relative to a cleaned/*.ts file. */
const TYPES_RELATIVE_IMPORT = '../../rules/rulebook.types';

/** Serialize a string for a TypeScript single-quoted literal. */
function quote(value: string): string {
  return JSON.stringify(value);
}

/** Render one Rule as a typed object literal (for `<game>.ts` files). */
function renderRule(rule: Rule): string {
  const body = rule.body.map((p) => `      ${quote(p)},`).join('\n');
  return [
    '  {',
    `    id: ${quote(rule.id)},`,
    `    game: ${quote(rule.game)},`,
    `    heading: ${quote(rule.heading)},`,
    '    body: [',
    body,
    '    ],',
    `    order: ${rule.order},`,
    '  },',
  ].join('\n');
}

/** Render the per-game module (e.g., `8-ball.ts`). */
function renderGameModule(slug: string, rules: Rule[]): string {
  const body = rules.map(renderRule).join('\n');
  return [
    `// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.`,
    `import type { Rule } from ${quote(TYPES_RELATIVE_IMPORT)};`,
    '',
    `export const rules: Rule[] = [`,
    body,
    `];`,
    `export default rules;`,
    '',
  ].join('\n');
}

/** Render the `index.ts` module (metadata + games list + idMap). */
function renderIndex(index: RulebookIndex): string {
  const games = index.games
    .map(
      (g) =>
        `    { slug: ${quote(g.slug)}, name: ${quote(g.name)}, ruleCount: ${g.ruleCount} },`,
    )
    .join('\n');
  const idMapEntries = Object.entries(index.idMap)
    .map(
      ([k, v]) =>
        `    [${quote(k)}]: { game: ${quote(v.game)}, ruleId: ${quote(v.ruleId)} },`,
    )
    .join('\n');
  return [
    `// Auto-generated by scripts/clean-rulebook.ts. Do not edit by hand.`,
    `import type { RulebookIndex } from ${quote(TYPES_RELATIVE_IMPORT)};`,
    '',
    `export const index: RulebookIndex = {`,
    `  publisher: ${quote(index.publisher)},`,
    `  edition: ${quote(index.edition)},`,
    `  sourcePdfUrl: ${quote(index.sourcePdfUrl)},`,
    `  defaultGame: ${quote(index.defaultGame)},`,
    `  games: [`,
    games,
    `  ],`,
    `  idMap: {`,
    idMapEntries,
    `  },`,
    `};`,
    `export default index;`,
    '',
  ].join('\n');
}

/**
 * Write every game module + the index. Creates the output directory if needed.
 *
 * @param rulesByGame Map of game slug to that game's parsed rules, in order.
 * @param games       Metadata for every game we're emitting.
 * @param edition     ISO-8601 date of the source edition (e.g., "2023-06-01").
 * @param sourcePdfUrl URL of the publisher-hosted source PDF for R11 attribution.
 * @param defaultGame Slug of the game shown on a cold `/rules` visit.
 */
export function writeRulebookModules(args: {
  rulesByGame: Record<string, Rule[]>;
  games: GameMeta[];
  edition: string;
  sourcePdfUrl: string;
  defaultGame: string;
}): void {
  const { rulesByGame, games, edition, sourcePdfUrl, defaultGame } = args;
  mkdirSync(OUTPUT_DIR, { recursive: true });

  for (const g of games) {
    const rules = rulesByGame[g.slug] ?? [];
    writeFileSync(join(OUTPUT_DIR, `${g.slug}.ts`), renderGameModule(g.slug, rules));
  }

  const index: RulebookIndex = {
    publisher: 'CSI',
    edition,
    sourcePdfUrl,
    defaultGame,
    games: games.map((g) => ({
      slug: g.slug,
      name: g.name,
      ruleCount: (rulesByGame[g.slug] ?? []).length,
    })),
    idMap: Object.fromEntries(
      games.flatMap((g) =>
        (rulesByGame[g.slug] ?? []).map((r) => [
          `${g.slug}:${r.id}`,
          { game: g.slug, ruleId: r.id },
        ]),
      ),
    ),
  };

  writeFileSync(join(OUTPUT_DIR, 'index.ts'), renderIndex(index));
}
