-- ============================================================================
-- MESSAGING OVERHAUL — PHASE 1 — UNIT 2
-- messages + members schema extensions
-- ============================================================================
--
-- Adds the schema mechanisms used by Units 3–5 of Phase 1 (auto-creation
-- utilities, season-activation trigger, roster + captain lifecycle triggers).
--
--   * messages.is_system           — flag distinguishing system-generated
--                                    rows (trigger-posted "Sally joined the
--                                    team") from user-authored rows.
--   * messages.sender_id           — relaxed from NOT NULL to NULLABLE so
--                                    system messages can have no sender.
--   * messages_is_system_shape     — paired CHECK that locks the invariant:
--                                    every row is EITHER a system message
--                                    with NULL sender OR a user message
--                                    with a non-NULL sender. No other shape.
--   * members.profanity_onboarding_completed_at
--                                  — timestamp set when the user makes a
--                                    choice on the Unit 9 onboarding modal.
--                                    Per-user, multi-device-safe (replaces
--                                    a localStorage approach).
--   * members.deleted_at           — soft-delete timestamp. Required by Unit
--                                    5's member soft-delete trigger (the
--                                    captain account-deletion case from D24
--                                    of the brainstorm). NULL = active.
--
-- ----------------------------------------------------------------------------
-- INTENTIONAL OMISSION: NO RLS POLICIES IN THIS MIGRATION
-- ----------------------------------------------------------------------------
-- The original plan for Unit 2 called for two RLS additions:
--   (a) INSERT policy on messages blocking authenticated users from setting
--       is_system = true (so only triggers / service_role can post system
--       messages — defense against spoofing).
--   (b) Row-owner-scoped UPDATE policy on members covering the new columns
--       so User A cannot write User B's profanity_onboarding_completed_at
--       or deleted_at.
--
-- Both are dropped from THIS migration because RLS itself is currently
-- DISABLED on `messages` and `members` (rowsecurity = false) — adding
-- policies to a table with RLS off is a no-op. RLS was intentionally
-- removed during development to avoid debugging time costs. Production has
-- no real users yet, so the gap is theoretical.
--
-- The CHECK constraint added below DOES protect at the schema layer: every
-- row must have the right (is_system, sender_id) shape regardless of who's
-- inserting. That covers data integrity. It does NOT prevent a malicious
-- authenticated user from inserting a row with is_system = true (with a
-- legitimately-null sender) and spoofing a system message. That gate
-- requires the RLS INSERT policy described above and lands as part of a
-- separate dedicated RLS-enablement effort, not Phase 1.
--
-- See: docs/plans/2026-05-09-001-feat-messaging-overhaul-phase-1-plan.md (Unit 2)
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. messages.is_system + nullable sender_id + paired CHECK
-- ----------------------------------------------------------------------------

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS is_system boolean NOT NULL DEFAULT false;

-- All existing rows already satisfy is_system = false (the default), so the
-- subsequent nullable+CHECK conversion is safe without a separate backfill.

ALTER TABLE messages
  ALTER COLUMN sender_id DROP NOT NULL;

-- Drop+recreate idiom for the shape CHECK so the migration is re-runnable
-- against an environment where a prior attempt left a stale constraint.
ALTER TABLE messages
  DROP CONSTRAINT IF EXISTS messages_is_system_shape;

ALTER TABLE messages
  ADD CONSTRAINT messages_is_system_shape
  CHECK (
    (is_system = true  AND sender_id IS NULL)
    OR
    (is_system = false AND sender_id IS NOT NULL)
  );

COMMENT ON COLUMN messages.is_system IS
  'TRUE when this message was generated by a trigger / SECURITY DEFINER function (e.g., "Sally joined the team"). When TRUE, sender_id is NULL and the message is rendered with the system-message visual variant. When FALSE, sender_id is required.';

COMMENT ON COLUMN messages.sender_id IS
  'Member who sent this message. NULL for system messages (is_system = true); otherwise required. The paired CHECK constraint messages_is_system_shape enforces this invariant at the schema layer.';


-- ----------------------------------------------------------------------------
-- 2. members.profanity_onboarding_completed_at
-- ----------------------------------------------------------------------------

ALTER TABLE members
  ADD COLUMN IF NOT EXISTS profanity_onboarding_completed_at timestamp with time zone;

COMMENT ON COLUMN members.profanity_onboarding_completed_at IS
  'Timestamp when the user made an explicit Yes/No choice on the first-load profanity-filter onboarding modal (Unit 9). NULL = modal not yet completed, modal re-appears at next app load. Set once and never modified — explicit "Decide later" / Escape / backdrop closes the modal without writing this column.';


-- ----------------------------------------------------------------------------
-- 3. members.deleted_at  (soft-delete)
-- ----------------------------------------------------------------------------

ALTER TABLE members
  ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;

COMMENT ON COLUMN members.deleted_at IS
  'Soft-delete timestamp. NULL = active member. Set when a member is deleted/suspended; Unit 5''s member-deletion trigger reads NULL→timestamp transitions and updates conversation_participants.left_at for every chat the member was in (captain account-deletion case per D24). Prefer soft delete to hard delete so chat history attribution remains coherent.';
